#!/bin/bash
#skripti algus
echo -n "tarnide arv: "
read tarnide_arv
for (( i = 1; i <= 5; i++ ))
	do
if (( $i == 1 || $i ==5))
then
echo -n  $i". "
for (( j =1; j <= 5; j++ ))
	do
		echo -n "*"
	done
	echo ""
else
echo -n $i". "
echo -n "*"
	for (( q =2; q <= 4; q++))
do
echo -n " "
done
echo "*"
fi
done
