#!/bin/bash
#skripti algus
echo -n "ridade arv: "
read ridade_arv
var1=$r
var2=$r
for (( i = 1; i <= $ridade_arv; i++ ))
	do
echo -n $i". "
for (( j = 1; j <= $ridade_arv-i; j++ ))
	do
		echo -n " "
	done
for (( k = 1; k <=i; k++))
do
	echo -n "*"
done
echo ""
done
